Create rus.ini
poggit-orphanage/SimpleAuthHelper pull request #2
Opened 2019-10-25 05:05 UTC by artemiyculbert

I translated your plugin into Russian.

2019-10-25 09:23 UTC, SOF3 requested changes

2019-10-25 09:23 UTC, SOF3 commented on resources/messages/rus.ini
> +"%1%-mode"="%1%-mode"
This wasn't translated

2019-10-25 09:23 UTC, SOF3 commented on resources/messages/rus.ini
> +"<nagme>"="yes"
I don't think this is needed

2019-10-26 01:07 UTC, Awzaw approved these changes

2026-04-05 13:04 UTC, closed without merging